### PR TITLE
acorn 8, esm, mocha

### PR DESCRIPTION
**Pull request by mbostock**
This:

* Upgrades to Acorn 8, fixing #64.
* Upgrades yarn.lock.
* Changes the default ecmaVersion from 12 to 13.
* Adopts ES modules, replacing standard-things/esm.
* Adopts Mocha, replacing Tap.
* Adopts ESLint in GitHub actions.
* Requires Node 14+.
* Drops experimental parseModule functionality.

We could do this change more minimally, but I think we’re going to want to do this in the near future anyway, so we might as well tie breaking changes together to minimize the number of major version bumps.

### CODE REVIEW

**Comment by mbostock** [comment]
If you want to compare to the pre-Tap snapshots of yore:

https://github.com/observablehq/parser/compare/812e84eba1cdff328b53839bf27e97676a9b6192~...mbostock/update-acorn

**Comment by sydneypalumbo** [comment]
sorry I've been slow to get to this! one thing I just wanted to call out is that we do use `peekId` when constructing document history currently in order to get cell names (we could either remove that logic now or do a normal parse if we wanted to keep it)

**Comment by mbostock** [comment]
Okay, I’ll restore the peekId functionality.

**Comment by mbostock** [comment]
Okay @sydneypalumbo this should be ready for another look! Thanks.

**Review by sydneypalumbo — APPROVED** [review]
👍

**Pull request merged**
